FrontEnd/ProjectFinder.Web/Controllers/GitHubFinderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjectFinder.Web.Models;
using ProjectFinder.Web.Service.IService;

namespace ProjectFinder.Web.Controllers;

public class GitHubFinderController : Controller
{
    private readonly IGitHubFinderService _gitHubFinderService;
    private readonly IGitHubAPIService _gitHubAPIService;

    public GitHubFinderController(IGitHubFinderService gitHubFinderService, IGitHubAPIService gitHubAPIService)
    {
        _gitHubFinderService = gitHubFinderService;
        _gitHubAPIService = gitHubAPIService;
    }

    public IActionResult Finder()
    {
        return View();
    }

    [HttpGet]
    // [Authorize(Roles = $"{SD.ADMINISTRATOR},{SD.COSTUMER}")]
    public async Task<IActionResult> Repositories(GitHubFinderDto gitHubFinderDto)
    {
        if (string.IsNullOrWhiteSpace(gitHubFinderDto.ProjectName))
        {
            TempData["error"] = "please enter a project name";
            return RedirectToAction(nameof(Finder));
        }

        ViewData["FinderModel"] = gitHubFinderDto;
        List<RepositoryDto> repositories = new();
        ResponseDto response = await _gitHubFinderService.FindAsync(gitHubFinderDto.ProjectName);

        if (response.Result == null)
        {
            response = await _gitHubAPIService.GetRepositoriesAsync(gitHubFinderDto.ProjectName);
            gitHubFinderDto.Repositories = response.Result.ToString();
            response = await _gitHubFinderService.SaveAsync(gitHubFinderDto);
        }

        if (response.Result != null && response.IsSuccess)
        {
            repositories = JsonConvert.DeserializeObject<List<RepositoryDto>>(Convert.ToString(response.Result));
        }
        else
        {
            TempData["error"] = response.Message;
            return RedirectToAction(nameof(Finder));
        }

        return View(repositories);
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(string projectName)
    {
        if (string.IsNullOrEmpty(projectName))
        {
            return BadRequest();
        }

        await _gitHubFinderService.DeleteAsync(projectName);
        return Ok(projectName);
    }
}

FrontEnd/ProjectFinder.Web/Views/GitHubFinder/Finder.cshtml
@* @model GitHubFinderDto *@

<div class="text-center">
    <h1>Git Finder</h1>
    <p>Find git's project by name project</p> 
    <div class="row justify-content-center">
        <div class="col-md-6 mx-auto">
            <form class="input-group col-md-6" asp-controller="GitHubFinder" asp-action="Repositories" method="get" onsubmit="return searchForm()">
                <input class="form-control" type="search" id="searchInput" name="ProjectName" placeholder="git's project name..." aria-label="git's project name">
                <span class="input-group-text">
                    <button class="btn btn-link text-dark px-3" type="submit" name="ProjectName" id="searchButton"><i class="bi bi-search"></i></button>
                </span>
                <span class="input-group-text text-danger" style="display: none;" id="resetSpan">
                    <button class="btn btn-link text-danger px-3" type="button" id="resetButton" onclick="resetForm()"><i class="bi bi-arrow-clockwise"></i></button>
                </span>
            </form>

            <script>
                function searchForm() {
                    var projectName = document.getElementById("searchInput").value;
                    if (projectName.trim() === "") {
                        alert("Project name cannot be empty");
                        return false;
                    }
                    return true;
                }
            </script>       
    </div>   
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FrontEnd/ProjectFinder.Web/Views/GitHubFinder/Repositories.cshtml
@model IEnumerable<RepositoryDto>

@{
    var finder = ViewData["FinderModel"] as GitHubFinderDto;
}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a asp-controller="GitHubFinder" asp-action="Finder">Finder</a></li>
  <li class="breadcrumb-item active">Repositories</li>
</ol>

<partial name="Finder" model=finder />

<br />

<div>
<form method="get">
    <div class="container border p-4">  
        <div class="row text-center">
            @if (Model != null && Model.Count() > 0)
            {
                <p>@Model.Count() repositories found </p>
            }
            else
            {
                <p>No repositories found for '@(finder != null ? finder.ProjectName : "unknown project")'</p>
            }
        </div> 
        <div class="row">
            @if (Model != null && Model.Any())
            {
                foreach (var repository in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-header">
                                <h5 class="my-0 font-weight-normal">@repository.Name</h5>
                            </div>
                            <div class="card-body">
                                <h6 class="card-title">Author: @repository.Owner.Author</h6>
                                <h6 class="card-text">Stargazers: @repository.Stargazers</h6>
                                <h6 class="card-text">Watchers: @repository.Watchers</h6>
                                <a href="@repository.RepositoryUrl" class="btn btn-primary">View Details</a>
                            </div>
                        </div>
                    </div>
                }
            }   
        </div>
    </div>
</form>
</div>

<script>
    document.addEventListener('DOMContentLoaded',function () {
      var searchInput = document.getElementById("searchInput");
      var resetSpan = document.getElementById("resetSpan");
      resetSpan.style.display = "inline";
        if (searchInput) {
            searchInput.placeholder = '@(finder != null ? finder.ProjectName : "git's project name...")';
        }
    });
</script> 

<script>
    function resetForm() {
        var search = document.getElementById("searchInput");
        if(confirm("Are you sure you want to reset and delete the found projects?")) {
            $.ajax({
                url: '@Url.Action("Delete", "GitHubFinder")', 
                type: 'DELETE',
                data: { projectName: search.placeholder },
                success: function (response) {
                    document.querySelector('.container.border.p-4').innerHTML = '';
                    search.placeholder = "git's project name...";
                    search.focus();
                    alert("Projects deleted successfully.");
                },
                error: function () {
                    alert('Error deleting projects.');
                }
            });
        }
    }
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}